#配置https的端口
server:
  port: 8080

spring:
  # redis
  redis:
    host: localhost
    database: 0
    port: 6379
    lettuce:
      pool:
        min-idle: 5
        max-wait: 30000
        max-active: 100
    timeout: 2000
  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
# 应用名称
  application:
    name: EzKeeper
# 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# 数据源名称
    name: defaultDataSource
# 数据库连接地址
    url: jdbc:mysql://127.0.0.1:3306/keeper?serverTimezone=UTC
# 数据库用户名&密码：
    username: root
    password: root
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis-plus:
  mapper-locations: classpath:/mapperXml/*.xml
#指定Mybatis的实体目录
  type-aliases-package: com.example.ezkeeper.model
#Mybatis 二级缓存
  configuration:
    cache-enabled: true

#账单每页数量
bill:
  pageSize: 10

#凭证加密算法
CredentialsMatcher:
  A: MD5
  C: 123

#sql日志显示
logging:
  level:
    com:
      example:
        ezkeeper:
          mappers: debug
